"""Domain enumerations used across models (stored as plain strings).

Kept as string constants (not native DB enums) so the prototype can evolve the
value set without migrations.
"""
from __future__ import annotations


class EngagementType:
    REGULAR = "REGULAR"
    PROBATIONARY = "PROBATIONARY"
    PROJECT_BASED = "PROJECT_BASED"
    FIXED_TERM = "FIXED_TERM"
    DAILY_PAID = "DAILY_PAID"
    HOURLY_PAID = "HOURLY_PAID"
    PART_TIME = "PART_TIME"
    CONSULTANT_INDIVIDUAL = "CONSULTANT_INDIVIDUAL"
    CONSULTANT_COMPANY = "CONSULTANT_COMPANY"
    CONTRACTOR = "CONTRACTOR"
    OJT = "OJT"
    TRAINEE = "TRAINEE"

    ALL = [
        REGULAR, PROBATIONARY, PROJECT_BASED, FIXED_TERM, DAILY_PAID, HOURLY_PAID,
        PART_TIME, CONSULTANT_INDIVIDUAL, CONSULTANT_COMPANY, CONTRACTOR, OJT, TRAINEE,
    ]
    CONSULTANT_TYPES = [CONSULTANT_INDIVIDUAL, CONSULTANT_COMPANY]


class EngagementStatus:
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    ON_LEAVE = "ON_LEAVE"
    SUSPENDED = "SUSPENDED"
    SEPARATED = "SEPARATED"
    COMPLETED = "COMPLETED"
    TERMINATED = "TERMINATED"
    RESIGNED = "RESIGNED"
    RETIRED = "RETIRED"


class PayrollStatus:
    DRAFT = "DRAFT"
    CALCULATED = "CALCULATED"
    FOR_REVIEW = "FOR_REVIEW"
    APPROVED = "APPROVED"
    LOCKED = "LOCKED"
    BANK_FILE_GENERATED = "BANK_FILE_GENERATED"
    PAID = "PAID"
    CLOSED = "CLOSED"
    VOID = "VOID"


class PayrollFrequency:
    MONTHLY = "MONTHLY"
    SEMI_MONTHLY = "SEMI_MONTHLY"
    WEEKLY = "WEEKLY"
    DAILY = "DAILY"
    HOURLY = "HOURLY"
    MILESTONE = "MILESTONE"
    RETAINER = "RETAINER"


class ObligationType:
    SSS_LOAN = "SSS_LOAN"
    PAGIBIG_LOAN = "PAGIBIG_LOAN"
    COMPANY_LOAN = "COMPANY_LOAN"
    SALARY_LOAN = "SALARY_LOAN"
    CASH_ADVANCE = "CASH_ADVANCE"
    TRAVEL_ADVANCE = "TRAVEL_ADVANCE"
    EMERGENCY_LOAN = "EMERGENCY_LOAN"
    GADGET_INSTALLMENT = "GADGET_INSTALLMENT"
    EQUIPMENT_INSTALLMENT = "EQUIPMENT_INSTALLMENT"
    COOPERATIVE_LOAN = "COOPERATIVE_LOAN"
    OTHER = "OTHER"


class ProjectStatus:
    PLANNING = "PLANNING"
    ACTIVE = "ACTIVE"
    ON_HOLD = "ON_HOLD"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
